// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: client1req.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Client1Request_CreateUser_FullMethodName = "/client1_request.Client1Request/CreateUser"
)

// Client1RequestClient is the client API for Client1Request service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Client1RequestClient interface {
	CreateUser(ctx context.Context, in *UserDetails, opts ...grpc.CallOption) (*UserResponse1, error)
}

type client1RequestClient struct {
	cc grpc.ClientConnInterface
}

func NewClient1RequestClient(cc grpc.ClientConnInterface) Client1RequestClient {
	return &client1RequestClient{cc}
}

func (c *client1RequestClient) CreateUser(ctx context.Context, in *UserDetails, opts ...grpc.CallOption) (*UserResponse1, error) {
	out := new(UserResponse1)
	err := c.cc.Invoke(ctx, Client1Request_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Client1RequestServer is the server API for Client1Request service.
// All implementations must embed UnimplementedClient1RequestServer
// for forward compatibility
type Client1RequestServer interface {
	CreateUser(context.Context, *UserDetails) (*UserResponse1, error)
	mustEmbedUnimplementedClient1RequestServer()
}

// UnimplementedClient1RequestServer must be embedded to have forward compatible implementations.
type UnimplementedClient1RequestServer struct {
}

func (UnimplementedClient1RequestServer) CreateUser(context.Context, *UserDetails) (*UserResponse1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedClient1RequestServer) mustEmbedUnimplementedClient1RequestServer() {}

// UnsafeClient1RequestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Client1RequestServer will
// result in compilation errors.
type UnsafeClient1RequestServer interface {
	mustEmbedUnimplementedClient1RequestServer()
}

func RegisterClient1RequestServer(s grpc.ServiceRegistrar, srv Client1RequestServer) {
	s.RegisterService(&Client1Request_ServiceDesc, srv)
}

func _Client1Request_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Client1RequestServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Client1Request_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Client1RequestServer).CreateUser(ctx, req.(*UserDetails))
	}
	return interceptor(ctx, in, info, handler)
}

// Client1Request_ServiceDesc is the grpc.ServiceDesc for Client1Request service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Client1Request_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "client1_request.Client1Request",
	HandlerType: (*Client1RequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Client1Request_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client1req.proto",
}
